### ISSUE TITLE
Error 429?

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#321] opened 2019-12-14 20:22 UTC
![image](https://user-images.githubusercontent.com/1057035/70854110-3a8ca180-1e85-11ea-9940-fbced707c99a.png)
When attempting to fetch any video information, this is the error I'm running into, anyone else struggling with this?

**Comment by Tyrrrz** [comment] 2019-12-14 20:29
Duplicate of #292

**Closed by Tyrrrz** 2019-12-14 20:29 UTC
Labels: duplicate
