### ISSUE TITLE
Unable to process age-restricted video

### ISSUE THREAD

**Issue by WhiteLionATX** [Tyrrrz/YoutubeExplode#110] opened 2018-04-17 16:59 UTC
I found a problem that should be solved (V4.0 updated Dec. 2017) but its still there:
The link to the video will cause an exception with message:
`{"Video [yLnmR6PXzGY] is not available and cannot be processed.\r\nError code: 150\r\nError reason: Sign in to confirm your age"}`
`https://www.youtube.com/watch?v=yLnmR6PXzGY`

Any solution for that ? - Or / How can I give the credentials of my "logged in yt-user" where I confirmed my age ? some example code would be nice... so I could solve myself ... I think. Thanx in advanced !

**Comment by remiX-** [comment] 2018-04-17 17:06
I had this to when trying to download a playlist. I added a try catch around everything so it wouldn't crash the program. It just skips those videos though.

I hope there is a way to sign in with a users details to solve this. and then the user could manage their account from outside of YouTube possibly.

**Comment by Tyrrrz** [comment] 2018-04-17 17:08
Interesting, maybe they've changed something again.

You can theoretically log in using an `HttpClient` beforehand and then pass it as a constructor parameter to `YoutubeClient` so that it re-uses the stored cookies.

**Comment by Tyrrrz** [comment] 2018-04-17 17:35
And a great pull request too 😛

**Comment by remiX-** [comment] 2018-04-17 17:39
Indeed it would be :D .. I only found out about this wonder YouTubeExplode a few weeks ago and only started using it recently. Don't know much about Http stuff in C# yet sadly :(

**Comment by TheOneAmir** [comment] 2018-04-19 04:14
I was going to give it a go but it seems alright with the latest version of the code. Perhaps, there is more to the problem?

**Comment by Tyrrrz** [comment] 2018-04-19 08:15
The video in OP has been removed: https://www.youtube.com/watch?v=yLnmR6PXzGY

**Comment by TheOneAmir** [comment] 2018-04-25 06:30
That video has been removed as well, but yes, I actually tried with multiple age restricted videos on DemoWpf and they all worked fine. Example link:
youtube.com/watch?v=6LZM3_wp2ps

![image](https://user-images.githubusercontent.com/5401094/39229400-8065d028-4817-11e8-8b0b-0de3d0188a2b.png)

**Comment by SlowLogicBoy** [comment] 2018-05-02 05:40
Nope:
```csharp
#! "netcoreapp2.0"

#r "nuget: YoutubeExplode, *"

using YoutubeExplode;
using YoutubeExplode.Models.MediaStreams;
var yt = new YoutubeClient();

var streams = await yt.GetVideoMediaStreamInfosAsync("6LZM3_wp2ps");
var videoStream = streams.Video.WithHighestVideoQuality();
await yt.DownloadMediaStreamAsync(videoStream, "6LZM3_wp2ps." + videoStream.Container);
```
Worked perfectly fine for me.

**Comment by Tyrrrz** [comment] 2018-05-02 20:41
Gonna wait 4 more days and close this if we're still unable to reproduce this.

**Comment by SlowLogicBoy** [comment] 2018-05-04 06:18
I was able to reproduce this on:
```csharp
YoutubeExplode.Exceptions.VideoUnavailableException: Video [hySoCSoH-g8] is not available and cannot be processed.
Error code: 150
Error reason: Sign in to confirm your age
```

**Comment by reddy04** [comment] 2018-05-14 13:20
I'm able to reproduce the issue when it is use in ASP.Net MVC application, hosted in third party server.
Below are the exception details:

**Error Message**: 
Video [OOQlCD5qMPY] is not available and cannot be processed.  Error code: 150  Error reason: Sign in to confirm your age

**StackTrace**:

   at YoutubeExplode.YoutubeClient.<GetVideoInfoAsync>d__35.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at YoutubeExplode.YoutubeClient.<GetVideoAsync>d__38.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Web.Controllers.YoutubeController.<Video>d__0.MoveNext() in C:\Users\vikram\codebase\repos\YoutubeDemo\Web\Controllers\YoutubeController.cs:line 45  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()     at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()     at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()     at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()     at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)     at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()     at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Sample Code**:

`
                // Client
                var client = new YoutubeClient();
                // Get Video Info
                Video details = await client.GetVideoAsync(id);
                // Get media stream info set
                MediaStreamInfoSet mediaStreamInfoSet = await client.GetVideoMediaStreamInfosAsync(id);

                return View("Index", new YoutubeVideo(id, mediaStreamInfoSet, details));`

**Comment by SlowLogicBoy** [comment] 2018-05-21 10:33
https://greasyfork.org/en/scripts/3848-bypass-youtube-age-verification-improved/code
this might help?

**Comment by InkyQuill** [comment] 2018-06-09 11:33
@Tyrrrz I have analyzed the code in youtube-dl and found the way to access age-restricted videos. You just need to simulate the inner request. Use this code in YutubeClient.Video.cs:

The new method:
```csharp
        private async Task<string> GetVideoInfoSimulatedAsync(string videoId, string sts = "")
        {
            var url = $"https://www.youtube.com/get_video_info?video_id={videoId}&eurl={Uri.EscapeDataString($"https://youtube.googleapis.com/v/{videoId}")}&sts={sts}&hl=en";
            return await _httpClient.GetStringAsync(url).ConfigureAwait(false);
        }
```

and some checks in GetVideoInfoAsync:
```csharp
                // A not so good way to check for age restriction, still works for our purposes
                if (videoInfo.ContainsKey("errorcode") && videoInfo["reason"].Contains("age"))
                {
                    raw = await GetVideoInfoSimulatedAsync(videoId, sts).ConfigureAwait(false);
                    videoInfo = UrlEx.SplitQuery(raw);
                }
```

**Comment by Tyrrrz** [comment] 2018-06-09 11:36
@InkyQuill what does simulate inner request mean?

**Comment by InkyQuill** [comment] 2018-06-09 11:38
It seems that youtube can read info for restricted videos, but needs to pass a certain url as `eurl` parameter with the `https://youtube.googleapis.com/v/<videoid>` data. Nothing more. I just use the words that youtube-dl author used for this.

**Comment by Tyrrrz** [comment] 2018-06-09 12:56
@InkyQuill can confirm this helped, thanks a lot!

**Closed** 2018-06-09 13:04 UTC
Labels: bug, caused by youtube

**Comment by SoftCircuits** [comment] 2022-08-24 20:35
@InkyQuill I'm still having this issue. I can't tell where your code goes? I'm using `YoutubeClient.GetmanifestAsync()` and `StreamManifest.Streams`. What objects is your code for? Where does `videoInfo` come from?

**Comment by Tyrrrz** [comment] 2022-08-24 21:44
@SoftCircuits this issue is from over 4 years ago, `videoInfo` doesn't exist anymore

**Comment by SoftCircuits** [comment] 2022-08-24 21:50
@Tyrrrz Ok, thanks. That explains why it made no sense. However, the error *Video 'AP5uM3QNfTA' does not contain any playable streams. Reason: 'This video may be inappropriate for some users.'.* does still exist.

**Comment by Tyrrrz** [comment] 2022-08-24 21:58
> However, the error _Video 'AP5uM3QNfTA' does not contain any playable streams. Reason: 'This video may be inappropriate for some users.'._ does still exist.

Yeah, I gave up on this cat and mouse game. There is no way to consistently retrieve media streams for restricted videos in an anonymous context.

**Comment by SoftCircuits** [comment] 2022-08-25 05:02
@Tyrrrz  Is there any way to add support for credentials in the library, that could be passed on to YouTube? It looks like [4K Video Downloader](https://www.4kdownload.com/howto/how-to-download-age-restricted-youtube-videos/2) supports this. I don't know enough about the internals to know what's involved.

**Comment by Tyrrrz** [comment] 2022-08-25 08:56
> @Tyrrrz Is there any way to add support for credentials in the library, that could be passed on to YouTube? It looks like [4K Video Downloader](https://www.4kdownload.com/howto/how-to-download-age-restricted-youtube-videos/2) supports this. I don't know enough about the internals to know what's involved.

[4K Video Downloader](https://www.4kdownload.com/howto/how-to-download-age-restricted-youtube-videos/2) is not a library, but an app. Logging in requires opening a browser for the user to type in their username and password, potentially solve a captcha, and also confirm via 2FA. You can do all that yourself in your app, then just extract cookies and pass it to YoutubeExplode via your own `HttpClient`.
