### ISSUE TITLE
youtubeClient.Videos.GetAsync(VideoId);   throw Exception（Every Video）

### ISSUE THREAD

**Issue by liuzuliang** [Tyrrrz/YoutubeExplode#800] opened 2024-07-12 05:57 UTC
### Version

6.3.16

### Platform

.NET Framework 4.7

### Steps to reproduce

![500](https://github.com/user-attachments/assets/0e8dff0d-da43-463a-8ac1-53cec135a9b7)

### Details

https://www.youtube.com/watch?v=4rF6Sz8xaUM

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by tomupson** [comment] 2024-07-17 20:06
Also seeing this with `StreamClient.GetManifestAsync`

**Comment by Tyrrrz** [comment] 2024-07-17 20:20
Works for me, so it may be a transient or a regional issue. Unfortunately, I can't investigate.

![image](https://github.com/user-attachments/assets/26e93c3b-7e6c-461a-a94d-c4a62034497d)

**Comment by tomupson** [comment] 2024-07-17 20:22
That's quite the video...

I'll look into my issue further

**Comment by Tyrrrz** [comment] 2024-08-07 00:23
Closing as I can't reproduce or investigate.

**Closed by Tyrrrz** 2024-08-07 00:23 UTC
Labels: invalid
