### ISSUE TITLE
NRE in parse keywords on GetVideoAsync

### ISSUE THREAD

**Issue by MasterDomino** [Tyrrrz/YoutubeExplode#176] opened 2018-11-02 18:00 UTC
```
   w YoutubeExplode.Internal.Parsers.VideoInfoParser.ParseKeywords()
   w YoutubeExplode.YoutubeClient.<GetVideoAsync>d__42.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   w OffLoad.Core.Services.MusicDownloadService.<DownloadAsync>d__8.MoveNext() w C:\\Users\\Master\\source\\repos\\OffLoadClient\\OffLoad.Core\\Services\\MusicDownloadService.cs:wiersz 40
```

if snippet needed, tell me.
same code since yesterday, it was working yesterday.

**Comment by Tyrrrz** [comment] 2018-11-02 21:12
Duplicate of #175

**Closed by Tyrrrz** 2018-11-02 21:12 UTC
Labels: duplicate
