### ISSUE TITLE
The app returns error

### ISSUE THREAD

**Issue by ghootifarangi** [Tyrrrz/YoutubeExplode#328] opened 2019-12-24 11:47 UTC
Hi

I have a website and my it uses this app for get videos from youtube. When users use this app for get videos, the app returns this error:

Response status code does not indicate success: 429 (Too Many Requests).

Please help me to resolve this problem.

**Comment by Tyrrrz** [comment] 2019-12-24 11:59
Duplicate of #292

**Closed by Tyrrrz** 2019-12-24 11:59 UTC
Labels: duplicate

**Comment by ghootifarangi** [comment] 2019-12-25 10:57
Apparently, youtube block this url (https://youtube.com/get_video_info?). Do you change this part of your app and get important data from source of video page (https://www.youtube.com/watch?v=)?

**Comment by ghootifarangi** [comment] 2019-12-25 10:58
test picofile.com

**Comment by ghootifarangi** [comment] 2019-12-25 10:58
test www.picofile.com

**Comment by ghootifarangi** [comment] 2019-12-25 10:58
test www.namasha.com

**Comment by Tyrrrz** [comment] 2019-12-25 12:02
Not sure what the question is
