### ISSUE TITLE
"Response status code does not indicate success: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by rekiem233** [Tyrrrz/YoutubeExplode#312] opened 2019-10-15 05:31 UTC
i receive this message on production webapi
help me please
"Response status code does not indicate success: 429 (Too Many Requests).

**Comment by rekiem233** [comment] 2019-10-15 05:31
seems how my ip was blocked

**Comment by wesbyte** [comment] 2019-10-15 20:10
I had the same error this week, I moved my website to another server but the error happened again error details:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests). at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at YoutubeExplode.YoutubeClient.d__35.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at YoutubeExplode.YoutubeClient.d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at YoutubeExplode.YoutubeClient.d__43.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at VB.VB$StateMachine_1_GetVideoStream.MoveNext()

Please advise ASAP. Thanks in advance.

**Comment by wesbyte** [comment] 2019-10-15 20:13
@rekiem233 Did you find a solution for this?

**Comment by rekiem233** [comment] 2019-10-16 19:43
publish my webapi over ovh.com vps installed in polonia and response ok
but i thing yt init block somes ips what instrumentation indicate umbral request as marked how spam

**Comment by wesbyte** [comment] 2019-10-17 01:25
@Tyrrrz  the error happened again for the third time this week and after moving the website to different servers, please help us and fix it ASAP.

**Comment by wesbyte** [comment] 2019-10-17 03:22
@rekiem233 Do you mean that message is caused by youtube itself?

**Comment by tradefuul** [comment] 2019-10-17 07:02
youtube is blocking your ip.  happening to me also.  i switched over to a vpn and it worked instantly.

**Comment by wesbyte** [comment] 2019-10-17 11:19
@tradefuul Did YouTube block your IP because of heavy traffic?

**Comment by Tyrrrz** [comment] 2019-10-20 10:10
Duplicate of #292

**Closed by Tyrrrz** 2019-10-20 10:10 UTC
Labels: duplicate
