### ISSUE TITLE
Video is unplayable. Reason: 'Please sign in'

### ISSUE THREAD

**Issue by johanolofsson72** [Tyrrrz/YoutubeExplode#834] opened 2024-10-22 09:57 UTC
### Version

6.4.3

### Platform

.NET9

### Steps to reproduce

var youtube = new YoutubeClient();
        var streamManifest = await youtube.Videos.Streams.GetManifestAsync("https://www.youtube.com/watch?v= djV11Xbc914");
        var streamInfo = streamManifest.GetMuxedStreams().TryGetWithHighestVideoQuality();
        if (streamInfo is null)
        {
            // Available streams vary depending on the video and it's possible
            // there may not be any muxed streams at all.
            // See the readme to learn how to handle adaptive streams.
            Console.Error.WriteLine("This video has no muxed streams.");
            return string.Empty;
        }
        return streamInfo.Url;

### Details

YoutubeExplode.Exceptions.VideoUnplayableException: Video 'djV11Xbc914' is unplayable. Reason: 'Please sign in'.
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, PlayerResponse playerResponse, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 212
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 276
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 292

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by SP-XD** [comment] 2024-10-23 18:41
Hi @johanolofsson72 , you check [this issue](https://github.com/Tyrrrz/YoutubeExplode/issues/794) may be help to you,

or you can [authenticate](https://github.com/Tyrrrz/YoutubeExplode#authentication) with  an throw-away account and try running it.

**Comment by Tyrrrz** [comment] 2024-10-26 12:27
Duplicate of #794

**Closed by Tyrrrz** 2024-10-26 12:27 UTC
Labels: duplicate
