### ISSUE TITLE
Exception when use Channels.GetUploadsAsync

### ISSUE THREAD

**Issue by ngochoaitn** [Tyrrrz/YoutubeExplode#520] opened 2021-03-29 16:09 UTC
Function: `Channels.GetUploadsAsync`
Channel Id: UC8WHyfTblB1QhzlJEZawLQw
Exception:
```
Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page
```

Thank.

**Comment by devnulli** [comment] 2021-04-04 17:17
hi.

the complete exception is:
`   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<>c__DisplayClass11_0.<<GetAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at YoutubeExplode.Internal.Retry.<WrapAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<GetAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeExplode.Videos.VideoClient.<GetVideoFromWatchPageAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeExplode.Videos.VideoClient.<GetAsync>d__10.MoveNext()`

thx for keeping this library up to the site

**Comment by Speyd3r** [comment] 2021-04-04 18:21
If you're using version 5, switch to version 6 preview 2, Youtube has a new cookie consent page that broke a lot

**Comment by devnulli** [comment] 2021-04-04 18:58
switching to 6.0.0-alpha2 did work for me

**Comment by Speyd3r** [comment] 2021-04-05 01:30
I forgot to mention, if you really need to use version 5 you can give the YoutubeClient a HttpClient that has following Cookie set:
Name: CONSENT
Value: YES+cb
Path: /
Domain: .youtube.com

**Comment by Tyrrrz** [comment] 2021-04-16 16:20
Duplicate of #501

**Closed by Tyrrrz** 2021-04-16 16:20 UTC
Labels: duplicate
