### ISSUE TITLE
Error in PlaylistClient.GetVideosAsync

### ISSUE THREAD

**Issue by iltanCaner987** [Tyrrrz/YoutubeExplode#508] opened 2021-03-01 06:21 UTC
**YoutubeExplode.Exceptions.TransientFailureException**: 'Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.'

And my simple code

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;
using YoutubeExplode;
using YoutubeExplode.Playlists;
using YoutubeExplode.Videos;
namespace test123
{
    public partial class Form1: Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        async void button1_Click(object sender, EventArgs e)
        {
            PlaylistClient cl = new YoutubeClient().Playlists;
            PlaylistId pId = new PlaylistId("https://www.youtube.com/playlist?list=PLI3Rhm3z9QM0EaILvoWLn_N8HbAbbrCDV");
            IReadOnlyList<Video> vids1 = await cl.GetVideosAsync(pId);
            List<Video> videos = vids1.ToList();
            foreach (var item in videos)
            {
                _ = MessageBox.Show(item.Title);
            }
        }
    }
}
```
Really should I just wait?

**Comment by Isayso** [comment] 2021-03-01 11:41
I think the issue is solved and we need to wait for a new Nuget package?

**Comment by iltanCaner987** [comment] 2021-03-01 12:15
> I think the issue is solved and we need to wait for a new Nuget package?

How do you know it's fixed?

**Comment by Isayso** [comment] 2021-03-01 12:18
I think I have seen a fix in pull request regarding the playlist get info error

**Comment by iltanCaner987** [comment] 2021-03-01 12:21
> I think I have seen a fix in pull request regarding the playlist get info error

Thanks. Waiting 👍

**Comment by Tyrrrz** [comment] 2021-03-01 16:15
You can use the pre-release package for now.
Duplicate of #457

**Closed by Tyrrrz** 2021-03-01 16:15 UTC
Labels: duplicate
