### ISSUE TITLE
Video watch page broken please try again later

### ISSUE THREAD

**Issue by finncast** [Tyrrrz/YoutubeExplode#535] opened 2021-04-21 11:58 UTC
Hi,
This has not been fixed in version 6 or o alpha and still exists in all versions. just with a few lines of code below you can test this.
This was raised already by another user and closed without being resolved
 public async Task YoutubeExplode()
        {

            var youtube = new YoutubeClient();

            var streamManifest = await youtube.Videos.Streams.GetManifestAsync("https://youtu.be/Rd-n1F38Ix8");

           var test= streamManifest.GetVideoOnlyStreams();
            
        }
The problem is  youtube.Videos.Streams.GetManifestAsync
Also when yo update you keep removing methods from previous versions and breaking things even more. Why not just fix what is broken?

**Comment by Isayso** [comment] 2021-04-22 07:17
I'm working to adapt my code to version 6.0, too, and get the same error, but the alpha versions before did work. 

Error:
"Video watch page is broken. Please try again in a few minutes."
from  


`using YoutubeExplode;`  
`using YoutubeExplode.Common;  `
`using YoutubeExplode.Videos;  `
`using YoutubeExplode.Playlists;  `
`using YoutubeExplode.Videos.Streams;  `
  
`            _youtube = new YoutubeClient();
`
`                var streamManifest = await _youtube.Videos.Streams.GetManifestAsync(videoId);
`

videoId is full Youtube url, to parse only the YT key get same error.

Thanks to look at!

**Comment by Tyrrrz** [comment] 2021-04-22 12:25
Duplicate of #530

**Closed by Tyrrrz** 2021-04-22 12:25 UTC
Labels: duplicate
