### ISSUE TITLE
get video from youtube not work

### ISSUE THREAD

**Issue by ghootifarangi** [Tyrrrz/YoutubeExplode#169] opened 2018-10-17 11:43 UTC
The application has been experiencing a problem receiving video and has encountered the following error:

Newtonsoft.Json.JsonReaderException
Additional text encountered after finished reading JSON content: }. Path '', line 1, position 15571.

please guide me

**Comment by dedady157** [comment] 2018-10-17 12:05
this is a dupe, the fix was added, i don't know if it was merged yet. but if it has just update and that should fix

**Comment by dedady157** [comment] 2018-10-17 12:05
just checked, it was merged, just update my man

**Comment by Tyrrrz** [comment] 2018-10-17 12:32
Duplicate of #164. The fix is already out.

**Closed** 2018-10-17 12:32 UTC
Labels: duplicate

**Comment by ghootifarangi** [comment] 2018-10-17 12:44
> Duplicate of #164. The fix is already out.

Has the latest version been modified and the problem has been resolved?

**Comment by Tyrrrz** [comment] 2018-10-17 12:46
Yes

**Comment by ghootifarangi** [comment] 2018-10-17 12:47
> Yes

tnx

**Comment by Tyrrrz** [comment] 2018-10-17 13:43
Please submit a pull request
