### ISSUE TITLE
Sign-in request when hosted in cloud

### ISSUE THREAD

**Issue by alramostpt** [Tyrrrz/YoutubeExplode#805] opened 2024-08-09 22:48 UTC
### Version

6.4

### Platform

.net8/debian

### Steps to reproduce

E.g. request GetVideo while hosted in EKS

### Details

When I run the GetVideo hosted locally (directly from local IIS or from Docker), the client is able to obtain the expected video metadata. Since a few days ago, when I run the exact same code hosted in cloud, the call to:
 await Http.GetStringAsync(
     $"https://www.youtube.com/watch?v={videoId}&bpctr=9999999999",
     cancellationToken
 )
(this happens inside GetVideoWatchPageAsync)

Get the following response:
{\"IsAvailable\":false,\"UploadDate\":null,\"LikeCount\":3190,\"DislikeCount\":null,\"PlayerResponse\":{\"PlayabilityError\":\"Sign in to confirm you\\u2019re not a bot\",\"IsAvailable\":false,\"IsPlayable\":false,\"Title\":null,\"ChannelId\":null,\"Author\":null,\"UploadDate\":null,\"Duration\":null,\"Thumbnails\":[],\"Keywords\":[],\"Description\":null,\"ViewCount\":null,\"PreviewVideoId\":null,\"DashManifestUrl\":null,\"HlsManifestUrl\":null,\"Streams\":[],\"ClosedCaptionTracks\":[]}}

The message "Sign in to confirm you're not a bot" is returned.

Any feedbacks on this?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment] 2024-08-09 23:15
Duplicate of #794

**Closed by Tyrrrz** 2024-08-09 23:15 UTC
Labels: duplicate
