### ISSUE TITLE
Exception Unhandled

### ISSUE THREAD

**Issue by UnboundGodz** [Tyrrrz/YoutubeExplode#234] opened 2019-04-24 10:19 UTC
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DemoConsole
  StackTrace:
   at DemoConsole.Program.<MainAsync>d__1.MoveNext() in C:\Users\UnboundGodz\Documents\Visual Studio 2019\YoutubeExplode-master\DemoConsole\Program.cs:line 39
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DemoConsole.Program.Main(String[] args) in C:\Users\UnboundGodz\Documents\Visual Studio 2019\YoutubeExplode-master\DemoConsole\Program.cs:line 60

![screenshot 114](https://user-images.githubusercontent.com/9623756/56650707-363d1b00-664d-11e9-833f-37d05a56de8f.jpg)

Ill have to look into this later, unless you know what might resolve it. To tired lol.

**Comment by Tyrrrz** [comment] 2019-04-24 11:01
Hi, this is a duplicate of #229

**Closed by Tyrrrz** 2019-04-24 11:01 UTC
Labels: duplicate
