### ISSUE TITLE
Could not find signature decipherer function name

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#254] opened 2019-06-21 15:13 UTC
Could not find signature decipherer function name.

**Comment by wleader** [comment] 2019-06-21 16:03
Just saw the same thing, Multiple different videos. 

   at YoutubeExplode.YoutubeClient.<GetCipherOperationsAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at YoutubeExplode.YoutubeClient.<GetVideoMediaStreamInfosAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by wleader** [comment] 2019-06-21 16:03
Oh, this is a duplicate of #252

**Comment by Tyrrrz** [comment] 2019-06-21 18:30
Duplicate of #252

**Closed by Tyrrrz** 2019-06-21 18:30 UTC
Labels: duplicate
