### ISSUE TITLE
Results in nothing (not even error) client.GetVideoMediaStreamInfosAsync

### ISSUE THREAD

**Issue by JustMeDaFaq** [Tyrrrz/YoutubeExplode#269] opened 2019-07-09 17:23 UTC
Hi, 
using following 2 lines results in nothing. The function doesnt get executed after "GetVideoMediaStreamInfosAsync" anymore and doesnt throw an error.
Installed the latest package via nuget.

var client = new YoutubeClient();
var streamInfoSet = await client.GetVideoMediaStreamInfosAsync("bnsUkE8i0tU");

**Comment by Tyrrrz** [comment] 2019-07-10 12:54
Closed as duplicate of #266

**Closed by Tyrrrz** 2019-07-10 12:54 UTC
Labels: duplicate
