### ISSUE TITLE
somes videos ,cannot play

### ISSUE THREAD

**Issue by luca233** [Tyrrrz/YoutubeExplode#167] opened 2018-10-16 14:58 UTC
From last Friday some videos cannot play.

Before this video can play https://www.rekiemtube.com/watch?v=fregObNcHC8
check it

if somebody have that isssue 

regards

**Comment by Tyrrrz** [comment] 2018-10-16 19:20
Duplicate of #164

**Closed by Tyrrrz** 2018-10-16 19:20 UTC
