### ISSUE TITLE
Search is throwing an exception

### ISSUE THREAD

**Issue by 1998MarkMueller** [Tyrrrz/YoutubeExplode#506] opened 2021-02-21 00:55 UTC
Whenever I call the function YoutubeExplode.Search.SearchClient.GetVideoAsync(string query), it throws this exception:

`Playlist response is broken.\r\nIn most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.\r\nTo resolve this error, please wait some time and try again.\r\nIf this issue persists, please report it on the project's GitHub page.`

Code:

```
 var youtube = new YoutubeClient();
 var videos = await youtube.Search.GetVideosAsync("undead corporation megalomania");
```

**Comment by Tyrrrz** [comment] 2021-02-22 00:16
Duplicate of #501

**Closed by Tyrrrz** 2021-02-22 00:16 UTC
Labels: duplicate
