### ISSUE TITLE
Channels.GetUploadsAsync not working

### ISSUE THREAD

**Issue by Anjoland** [Tyrrrz/YoutubeExplode#511] opened 2021-03-09 11:27 UTC
YoutubeExplode.Exceptions.TransientFailureException: 'Playlist response is broken.

In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.

To resolve this error, please wait some time and try again.

If this issue persists, please report it on the project's GitHub page.'

v5.1.9

I got this yesterday morning, waited 24 hours to see if it would clear up, sill having the issue.

**Comment by maurictg** [comment] 2021-03-09 11:57
Same problem here on v5.1.9, with `YoutubeClient.Playlists.GetAsync()`

**Comment by codedbycurtis** [comment] 2021-03-10 11:01
Most playlist response functionality is broken in version `5.1.9`. Until another major release, [`pre-release 6.0.0-alpha`](https://www.nuget.org/packages/YoutubeExplode/6.0.0-alpha) is the only version that currently works.

You can look at #501 for more information.

**Comment by Anjoland** [comment] 2021-03-10 17:34
Hey Curtis, thanks for the info, I updated to the alpha and that indeed did fix the issue.

**Comment by jakedacatman** [comment] 2021-03-19 01:18
I believe 6.0.0-alpha has it broken now as well; it used to work.

**Comment by codedbycurtis** [comment] 2021-03-19 01:58
> I believe 6.0.0-alpha has it broken now as well; it used to work.

Just checked on my end; seems to still be working for me - both querying and downloading.

What seems to be happening on your end?

**Comment by Tyrrrz** [comment] 2021-03-22 09:44
Appears to be effectively a duplicate of #501

**Closed** 2021-03-22 09:45 UTC
Labels: duplicate
