### ISSUE TITLE
Video watch page is broken

### ISSUE THREAD

**Issue by mon3104** [Tyrrrz/YoutubeExplode#530] opened 2021-04-18 07:46 UTC
Video watch page is broken when calling client.Videos.GetAsync(ID) in ver 6.0.0.
Been like this for the past 12 hours. From my understanding issue is solved in alpha2?
Any work arounds until then?

**Comment by Speyd3r** [comment] 2021-04-18 09:49
Its mostly a consent page Youtube has added, can you give the YoutubeClient a HttpClient that has following Cookie set:
Name: CONSENT
Value: YES+cb
Path: /
Domain: .youtube.com

but using alpha2 wold work too

**Comment by Tyrrrz** [comment] 2021-04-18 12:24
That cookie is sent in v6.0 as well

**Comment by Speyd3r** [comment] 2021-04-18 14:40
My bad, I didnt see the the recent update.

@mon3104 what video ID did you try? Any specific exception?

**Comment by mon3104** [comment] 2021-04-18 14:57
@Speyd3r noting in particular, just random videos. I remember I tried this one and I also tried to pass the full link instead of the ID as mentioned in the homepage.
https://youtu.be/H1wcU8BD0cQ

**Comment by Speyd3r** [comment] 2021-04-18 18:04
Worked flawlessly for me, would be good to know what exception you are getting with it, I just tried with both alpha2 and regular v6

**Comment by mon3104** [comment] 2021-04-18 19:45
@Speyd3r @Tyrrrz 

Tried again this evening with the same link shared above and this is the exception.

and this is the code.

static YoutubeClient _client = new YoutubeClient();
_video = await _client.Videos.GetAsync(@"https://www.youtube.com/watch?v=H1wcU8BD0cQ");

or 
videoID = YoutubeExplode.Videos.VideoId.TryParse(pastedLink);
_video = await _client.Videos.GetAsync(ID);

Nothing much changed from the previous working version using 5.xxx although at the end it was broken due to Youtube's changes. I only excluded some using statements (mainly YoutubeExplode.Internal) and a fix for getting Thumbnails.

Exception : 
at YoutubeExplode.Bridge.YoutubeController.d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Threading.Tasks.ValueTask`1.get_Result() at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult() at YoutubeExplode.Videos.VideoClient.d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Threading.Tasks.ValueTask`1.get_Result() at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()

![image](https://user-images.githubusercontent.com/46069880/115158342-f3707b00-a08d-11eb-9b71-a3465049b2f0.png)

**Comment by nycr0x** [comment] 2021-04-19 10:35
My problem its be contiune any body help ?

**Comment by Tyrrrz** [comment] 2021-04-19 11:33
@mon3104 does 6.0-alpha2 work for you?

**Comment by Tyrrrz** [comment] 2021-04-19 11:36
One thing you can do if it's reproducible consistently is to clone the repo and put a breakpoint here:

https://github.com/Tyrrrz/YoutubeExplode/blob/33744f03dc6f480cdca4d8e91c127a4d8e539b3f/YoutubeExplode/Bridge/YoutubeController.cs#L119

Then if it gets hit, copy the content of `raw` variable and paste it here. We'd be able to see what's wrong with the page you're getting.

**Comment by mon3104** [comment] 2021-04-19 11:39
@Tyrrrz I haven't tried alpha2 yet as direct update didn't work and had no time to clean and install it separately. I will try to debug and provide the data of raw variable tonight.

**Comment by mon3104** [comment] 2021-04-19 16:06
@Tyrrrz I am unable to decompile that far into the code and am unable to add the file into the solution (I take it because I'm compiling C# win forms. I might not have the knowledge to perform what you are asking at this point. Maybe I can follow up with some guidance...

**Comment by mon3104** [comment] 2021-04-19 17:10
@Tyrrrz was going to continue and try to see how to debug the issue and all of a sudden it just worked without any changes for any video... 🤯

**Comment by Reducer** [comment] 2021-04-19 17:17
I still have the problem if NuGet package 6.0.0 is installed, but not with 6.0.0-alpha2.
Checked the headers with fiddler and noticed that the consent cookie is not send with version 6.0.0.
Maybe this can be confirmed and/or be helpful for someone.

**Comment by mon3104** [comment] 2021-04-19 18:38
@Tyrrrz update : just installed alpha 2 and it works. One dependency that I had to add was "System.Text.Encoding.CodePages" however I assumed this was because I cleaned all dependencies and "started from scratch". Not sure if this dependency is by default or should be listed as a dependency for v6.0.0

**Comment by Tyrrrz** [comment] 2021-04-22 12:23
Thanks for looking into it.
Looking in Fiddler, the cookie does get sent though in v6.0. Unless I'm missing something?

![image](https://user-images.githubusercontent.com/1935960/115713500-bd2d4700-a37e-11eb-9510-2fb57e6772b8.png)

**Comment by Reducer** [comment] 2021-04-22 16:46
Thanks for investigation the issue.
I created a new "Windows Forms App (.NET Framework)" project and checked again, unfortunately the error still occurs.
The strange thing is that version v6.0.0-alpha2 works, but v6.0.0 does not. 
Maybe it is me who is missing something?

![grafik](https://user-images.githubusercontent.com/3178299/115752903-d9d77800-a39a-11eb-9d2c-a117b95d3077.png)

**Comment by Tyrrrz** [comment] 2021-04-22 19:25
Hm, it looks like in your screenshot it's actually sending additional cookies from somewhere. I wonder where they're coming from.

@Speyd3r's PR (which was released in alpha2) only set `CONSENT=YES+cb`

https://github.com/Tyrrrz/YoutubeExplode/pull/523/files

**Comment by Tyrrrz** [comment] 2021-04-22 19:28
If I use the old version, I get the expected `CONSENT=YES+cb` but also an additional cookie as well. Can anyone smarter than me explain where this is coming from? This is the first request sent by that specific `HttpClient`. 🤔 

![image](https://user-images.githubusercontent.com/1935960/115774267-09e24380-a3ba-11eb-99fb-acfedeb433bb.png)

**Comment by Tyrrrz** [comment] 2021-04-22 19:42
Ok nevermind, the older version sent a request to non-www URL first and those cookies we both see are set during redirect. But since `CONSENT=YES+cb` is present in both cases anyway, I'm leaning towards the assumption that some additional cookies (that were previously set on redirect) are also necessary.

@Reducer can you test this out by initializing `YoutubeClient` like this:

```csharp
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Add("Cookie", "CONSENT=YES+cb; YSC=DwKYllHNwuw");

var youtube = new YoutubeClient(httpClient);

// ...
```

**Comment by cata76** [comment] 2021-04-23 07:50
@Tyrrrz I tried to initialize YoutubeClient in the way you indicated. But it still doesn't work... :(

**Comment by Reducer** [comment] 2021-04-23 12:01
@Tyrrrz,
I figured out that the cookie is sent when the target framework is .NET 5.0, but is ignored when it is .NET 4.7.2.

So I tried a few things and I think that there is a different behavior of HttpClient and HttpClientHandler between .NET Core and .NET Framework. I found two approaches with which the cookie was sent with target framework 4.7.2.:

- Use HttpClientHandler with deactivated UseCookies

` using (var request = new HttpRequestMessage(HttpMethod.Get, url)) `
`// .. `
`var httpClient = new HttpClient(new HttpClientHandler {UseCookies = false}, true);`
`// .. `
`request.Headers.Add("Cookie", "CONSENT=YES+cb");`
`// .. `

- Add cookie to HttpClientHandler.CookieContainer (like in alpha 2)

` using (var httpClientHandler = new HttpClientHandler()) `
` using (var request = new HttpRequestMessage(HttpMethod.Get, url)) `
`// .. `
` httpClientHandler.CookieContainer.Add(new Cookie("CONSENT", "YES+cb", "/", ".youtube.com")); `
` var httpClient = new HttpClient(httpClientHandler);`
`// .. `

**Comment by Tyrrrz** [comment] 2021-04-23 13:29
If anyone can modify the source, can you check if removing `www.` here helps?

https://github.com/Tyrrrz/YoutubeExplode/blob/90915b2b8a2fa604b5adaebab6ebef66ef3b7df1/YoutubeExplode/Bridge/YoutubeController.cs#L104

**Comment by dunce** [comment] 2021-04-23 13:49
FYI, it seems Youtube is responding to American IPs differently than European ones.
I used a VPN to connect through the Netherlands, France and England and they all gave me an error.
Everything worked fine with American IP.

**Comment by DevElkami** [comment] 2021-04-23 14:13
> 
> 
> @Tyrrrz,
> I figured out that the cookie is sent when the target framework is .NET 5.0, but is ignored when it is .NET 4.7.2.
> 
> So I tried a few things and I think that there is a different behavior of HttpClient and HttpClientHandler between .NET Core and .NET Framework. I found two approaches with which the cookie was sent with target framework 4.7.2.:
> 
>     * Use HttpClientHandler with deactivated UseCookies
> 
> 
> `using (var request = new HttpRequestMessage(HttpMethod.Get, url))`
> `// .. `
> `var httpClient = new HttpClient(new HttpClientHandler {UseCookies = false}, true);`
> `// .. `
> `request.Headers.Add("Cookie", "CONSENT=YES+cb");`
> `// .. `
> 
>     * Add cookie to HttpClientHandler.CookieContainer (like in alpha 2)
> 
> 
> `using (var httpClientHandler = new HttpClientHandler())`
> `using (var request = new HttpRequestMessage(HttpMethod.Get, url))`
> `// .. `
> `httpClientHandler.CookieContainer.Add(new Cookie("CONSENT", "YES+cb", "/", ".youtube.com"));`
> ` var httpClient = new HttpClient(httpClientHandler);`
> `// .. `

@Reducer You're right. I change my code (I'm in 4.7.2) with your sample, and all is good ! Thx 👍

**Comment by Tyrrrz** [comment] 2021-04-23 15:08
> You're right. I change my code (I'm in 4.7.2) with your sample, and all is good ! Thx 👍

That still doesn't explain why it works in alpha-2 but not in stable though.

**Comment by Reducer** [comment] 2021-04-23 16:41
> That still doesn't explain why it works in alpha-2 but not in stable though.

I decompiled the alpha-2 package and this is completely different code than in the stable package.
In alpha 2 the cookie is set in the YoutubeClient class using the HttpClientHandler.CookieContainer, while in the stable version it is set in Bridge\YoutubeController class by adding it to the request header.

**Comment by Tyrrrz** [comment] 2021-04-23 17:23
> > That still doesn't explain why it works in alpha-2 but not in stable though.
> 
> I decompiled the alpha-2 package and this is completely different code than in the stable package.
> In alpha 2 the cookie is set in the YoutubeClient class using the HttpClientHandler.CookieContainer, while in the stable version it is set in Bridge\YoutubeController class by adding it to the request header.

Yes, that's true. However, it should end up working the same since cookies are just headers at the end of the day. At least that's my understanding, so if I'm wrong please explain it to me.

**Comment by Reducer** [comment] 2021-04-23 18:13
> 
> 
> > > That still doesn't explain why it works in alpha-2 but not in stable though.
> > 
> > 
> > I decompiled the alpha-2 package and this is completely different code than in the stable package.
> > In alpha 2 the cookie is set in the YoutubeClient class using the HttpClientHandler.CookieContainer, while in the stable version it is set in Bridge\YoutubeController class by adding it to the request header.
> 
> Yes, that's true. However, it should end up working the same since cookies are just headers at the end of the day. At least that's my understanding, so if I'm wrong please explain it to me.

I agree with you that it should work that way, so maybe that's why it was changed with .NET Core. Unfortunately I couldn't find a real explanation for this behavior, but it was described here: https://stackoverflow.com/a/13287224

**Comment by Tyrrrz** [comment] 2021-04-24 00:02
> > > > That still doesn't explain why it works in alpha-2 but not in stable though.
> > > 
> > > 
> > > I decompiled the alpha-2 package and this is completely different code than in the stable package.
> > > In alpha 2 the cookie is set in the YoutubeClient class using the HttpClientHandler.CookieContainer, while in the stable version it is set in Bridge\YoutubeController class by adding it to the request header.
> > 
> > 
> > Yes, that's true. However, it should end up working the same since cookies are just headers at the end of the day. At least that's my understanding, so if I'm wrong please explain it to me.
> 
> I agree with you that it should work that way, so maybe that's why it was changed with .NET Core. Unfortunately I couldn't find a real explanation for this behavior, but it was described here: https://stackoverflow.com/a/13287224

Hmm from that answer looks like setting `UseCookies = false` may help. So something like this:

```charp
var handler = new HttpClientHandler();
var httpClient = new HttpClient(handler, true);
handler.UseCookies = false;

var youtube = new YoutubeClient(httpClient);

// ...
```

**Comment by cata76** [comment] 2021-04-24 11:02
Using this solution works:

using (var httpClientHandler = new HttpClientHandler())
using (var request = new HttpRequestMessage(HttpMethod.Get, url))
// .. 
httpClientHandler.CookieContainer.Add(new Cookie("CONSENT", "YES+cb", "/", ".youtube.com"));
var httpClient = new HttpClient(httpClientHandler);
// ..

I made a web page to download both mp4 video and mp3 audio using YoutubeExplode

https://www.mezil.it/Youtube.html

Thanks!

**Comment by Tyrrrz** [comment] 2021-04-24 17:32
@cata76 can you also try the snippet in my previous comment? Does that also work?

**Comment by cata76** [comment] 2021-04-24 17:41
@Tyrrrz as soon as I can I try it and tell you

**Comment by Isayso** [comment] 2021-04-24 19:48
@Tyrrrz  its working for me

```cs
var handler = new HttpClientHandler();
var httpClient = new HttpClient(handler, true);
handler.UseCookies = false;

var youtube = new YoutubeClient(httpClient);
````

**Closed** 2021-04-30 23:25 UTC
Labels: bug, bug/can't reproduce, bug/caused by youtube

**Comment by opcodewriter** [comment] 2024-09-16 08:25
I'm suddenly getting this error.

Any help please on this?

**Comment by mugnap** [comment] 2024-09-16 17:35
Now I'm getting this error too, it started a few hours ago...
Any help?

**Comment by Metinak47** [comment] 2024-09-19 21:10
I have this error too. Sometimes I got error Video 'video code' is not available.
