### ISSUE TITLE
Produced Exception: 'System.Text.Json.JsonReaderException' in mscorlib.dll

### ISSUE THREAD

**Issue by Ts-Pytham** [Tyrrrz/YoutubeExplode#481] opened 2020-11-20 19:41 UTC
Hi there,

Today i was going to change something from the script and i did notice that a piece from the script doesn't work and it was working perfectly yersterday and is this part: <code>StreamManifest Stream = await youtube.Videos.Streams.GetManifestAsync(video.Id);</code>
the variable <code>video.Id</code> works perfectly, but when the program runs into the line before mentioned produces the exception: <code>'System.Text.Json.JsonReaderException'</code> and i haven't could fix it, this error showed up today, yesterday it was working fine.

**Comment by Tyrrrz** [comment] 2020-11-20 20:14
Duplicate of #479?

**Closed** 2020-11-23 16:11 UTC
Labels: duplicate
