### ISSUE TITLE
Cannot play a lot videos

### ISSUE THREAD

**Issue by kaduhsf** [Tyrrrz/YoutubeExplode#180] opened 2018-11-07 03:32 UTC
All was working but for now, alot videos don't play anymore, like this: https://www.youtube.com/watch?v=bo_efYhYU2A, showing this error message "Exception thrown: 'YoutubeExplode.Exceptions.ParseException' in mscorlib.dll"

**Comment by Tyrrrz** [comment] 2018-11-07 09:58
Duplicate of #179

**Closed by Tyrrrz** 2018-11-07 09:58 UTC
