### ISSUE TITLE
Crash when fetching playlist of a large channel

### ISSUE THREAD

**Issue by Montegro** [Tyrrrz/YoutubeExplode#557] opened 2021-06-10 13:58 UTC
### Version

6.0.2

### Details

For the last three days I've been running into this crash when attempting to fetch the video list of a large channel (in this instance, the Game Grumps) would anyone be able to help me figure out how to do what it's recommending I do?
![image](https://user-images.githubusercontent.com/1057035/121537830-469de480-c9d2-11eb-8655-973a0b1034b0.png)

### Steps to reproduce

Past a channel ID into your process, replacing UC with PL and have it fetch from a channel with a lot of videos.

**Comment by EmanueleSpadaro** [comment] 2021-06-10 21:52
As the exception message states, you mostly occur on HTTP 429 responses from YouTube, hence you make "Too Many Requests" in a really small frame of time, therefore you've been temporarily IP banned from YouTube.
It's not a bug, if you carefully read the message you could see that one possible solution is to include your YouTube account cookies to increase the threshold from which YouTube starts sending you 429's error.

**Comment by Tyrrrz** [comment] 2021-06-11 13:22
Exactly as @EmanueleSpadaro said.
Duplicate of / related to #453 #376 #292 #312 #273 #436 #321 #470 #500

**Closed by Tyrrrz** 2021-06-11 13:22 UTC
Labels: invalid

**Comment by Montegro** [comment] 2021-06-11 14:09
> 
> 
> As the exception message states, you mostly occur on HTTP 429 responses from YouTube, hence you make "Too Many Requests" in a really small frame of time, therefore you've been temporarily IP banned from YouTube.
> It's not a bug, if you carefully read the message you could see that one possible solution is to include your YouTube account cookies to increase the threshold from which YouTube starts sending you 429's error.

I'm a bit sick currently so forgive me, but uh, how would I go about including account cookies? Is there a fairly simple function I'm missing? Or is that sort of a manual thing.

**Comment by derech1e** [comment] 2021-06-11 14:57
> > As the exception message states, you mostly occur on HTTP 429 responses from YouTube, hence you make "Too Many Requests" in a really small frame of time, therefore you've been temporarily IP banned from YouTube.
> > It's not a bug, if you carefully read the message you could see that one possible solution is to include your YouTube account cookies to increase the threshold from which YouTube starts sending you 429's error.
> 
> I'm a bit sick currently so forgive me, but uh, how would I go about including account cookies? Is there a fairly simple function I'm missing? Or is that sort of a manual thing.

I think that is related to that Issue at the [YoutubeDownloader ](https://github.com/Tyrrrz/YoutubeDownloader)repository; https://github.com/Tyrrrz/YoutubeDownloader/issues/198#issuecomment-847413222

**Comment by Tyrrrz** [comment] 2021-06-11 15:46
> > As the exception message states, you mostly occur on HTTP 429 responses from YouTube, hence you make "Too Many Requests" in a really small frame of time, therefore you've been temporarily IP banned from YouTube.
> > It's not a bug, if you carefully read the message you could see that one possible solution is to include your YouTube account cookies to increase the threshold from which YouTube starts sending you 429's error.
> 
> I'm a bit sick currently so forgive me, but uh, how would I go about including account cookies? Is there a fairly simple function I'm missing? Or is that sort of a manual thing.

You would use the constructor of `YoutubeClient` that takes an instance of `HttpClient`. You can create an `HttpClient` and seed it with cookies via:

```csharp
var cookieContainer = new CookieContainer();
cookieContainer.Add("https://youtube.com", new Cookie("CookieName", "cookie_value"));

var httpClient = new HttpClient(new HttpClientHandler { CookieContainer = cookieContainer }, true);

var youtube = new YoutubeClient(httpClient);
```

To figure out which cookies to put, the easiest way is just to log in to YouTube in your browser and see which cookies you end up sending after that (via Network tab in dev console).
