### ISSUE TITLE
GetVideoAsync() Encoding parsing error 

### ISSUE THREAD

**Issue by SnGmng** [Tyrrrz/YoutubeExplode#249] opened 2019-06-15 20:07 UTC
if i run
`GetVideoAsync("lTEzfj8IAR0") `
it throws 
`System.ArgumentException: 'GB18030' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.`
It seems to occur only on some video ids, for example "lTEzfj8IAR0".

**Comment by Tyrrrz** [comment] 2019-06-15 20:09
wtf
can you give me the callstack?

**Comment by Tyrrrz** [comment] 2019-06-16 08:49
I can't reproduce this

**Comment by SnGmng** [comment] 2019-06-16 10:32
I can reproduce the error with following steps:
1. make a new uwp app project or a windows forms project
2. download youtube explode 4.7.2 via nuget
3. call `await yt.GetVideoAsync(lTEzfj8IAR0)`
4. in uwp there will occur 20 or more errors of this type, in winforms there will occurr 1 error of this type

Call stack:
<img width="869" alt="Screenshot_68" src="https://user-images.githubusercontent.com/38666407/59562882-b28f2180-9032-11e9-8f8d-2993ea8e447e.png">

**Comment by Tyrrrz** [comment] 2019-06-16 11:25
Ah, judging by the callstack it seems like AngleSharp is trying to get text encoding for whatever purpose and fails.
Looks like GB18030 is [some kind of Chinese charset](https://en.m.wikipedia.org/wiki/GB_18030), which may explain why I can't reproduce it myself.

**Comment by SnGmng** [comment] 2019-06-16 11:41
Im not from China tho, im from Germany, and GB18030 is not the only error, there are as i said 20 more errors. Here are all "charsets" from these errors:

In UWP:
`'GB18030','big5','windows-874' , 'windows-1250','windows-1251','windows-1252','windows-1253','windows-1254','windows-1255','windows-1256','windows-1257','windows-1258','iso-8859-2','iso-8859-3','iso-8859-4','iso-8859-5','iso-8859-13','ks_c_5601-1987','macintosh','x-mac-cyrillic','cp866','iso-8859-6','iso-8859-7','iso-8859-8','iso-8859-8-i','iso-8859-13','iso-8859-15',koi8-r','koi8-u','x-cp20936','hz-gb-2312','iso-2022-jp','iso-2022-kr','iso-2022-cn','shift_jis','euc-jp'`

In Windows Forms (.NET 4.5):
`'iso-2022-cn'`

**Comment by SnGmng** [comment] 2019-06-16 11:57
HlmlParser().Parse(raw) seems to be the issue.
<img width="741" alt="Screenshot_69" src="https://user-images.githubusercontent.com/38666407/59563770-8083bc80-903e-11e9-8292-09a63da755bf.png">

Here is the raw html data Anglesharp fails to parse: https://pastebin.com/JGe3h7Nt

**Comment by Tyrrrz** [comment] 2019-06-16 12:33
Can you post the value of `raw` in your screenshot?

**Comment by Tyrrrz** [comment] 2019-07-04 14:49
I switched from AngleSharp to LtGt so this error should be fixed in the upcomming version. If it's not, please re-open this issue.

**Closed by Tyrrrz** 2019-07-04 14:49 UTC
Labels: bug
