### ISSUE TITLE
Doesn't seem to work, it returns empty response

### ISSUE THREAD

**Issue by wesbyte** [Tyrrrz/YoutubeExplode#353] opened 2020-04-08 19:08 UTC
GetVideoMediaStreamInfosAsync doesn't return any result, please advise.

**Comment by mrklintscher** [comment] 2020-04-09 15:06
YouTube changed their deciphering method. We have to reengineer it.

**Comment by wesbyte** [comment] 2020-04-09 22:13
@mrklintscher Thanks for this, any ideas when this could be done?

**Comment by Tyrrrz** [comment] 2020-04-10 18:03
Working on it.
Duplicate of #333.

**Closed by Tyrrrz** 2020-04-10 18:03 UTC
Labels: duplicate
