### ISSUE TITLE
url_encoded_fmt_stream_map is null

### ISSUE THREAD

**Issue by omansak** [Tyrrrz/YoutubeExplode#317] opened 2019-12-02 08:57 UTC
Video works normally but url_encoded_fmt_stream_map is empty/null

Id : AYmeJlm7Gcg

**Comment by Tyrrrz** [comment] 2019-12-09 21:47
Duplicate of #310 by the looks of it

**Closed by Tyrrrz** 2019-12-09 21:47 UTC
Labels: duplicate

**Comment by omansak** [comment] 2019-12-15 16:36
Test Values :
Normal : Alr26K0F4EQ
Encrypted : ADxntEqPysA

**Comment by Tyrrrz** [comment] 2019-12-15 17:02
Try updating to 4.7.11

**Comment by omansak** [comment] 2019-12-15 17:44
@Tyrrrz yes i know you updated i just gived test values for future
