### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: value at Newtonsoft.Json.Linq.Extensions.

### ISSUE THREAD

**Issue by wesbyte** [Tyrrrz/YoutubeExplode#267] opened 2019-07-08 22:44 UTC
I am using the recent release of the package, all the videos are crashed with the below error message, please advise ASAP. Thanks in advance.

System.ArgumentNullException: Value cannot be null. Parameter name: value at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value) at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value) at YoutubeExplode.YoutubeClient.d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at YoutubeExplode.YoutubeClient.d__43.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at VB.VB$StateMachine_1_GetVideoStream.MoveNext()

**Comment by AlenToma** [comment] 2019-07-08 22:49
Yes i got that to, thay have changed the json, the library trying to find `sts` in the json and it fail

**Comment by ConsultantsCombined** [comment] 2019-07-09 01:06
Same

**Comment by Montegro** [comment] 2019-07-09 01:11
Same

**Comment by HamzaAnis** [comment] 2019-07-09 02:19
https://github.com/Tyrrrz/YoutubeExplode/blob/527112b42c01161650dde1fa33696daed47f5f2d/YoutubeExplode/YoutubeClient.Video.cs#L83

This is the issue. Someone should fix this and open a pull request so it functions again.

**Comment by rifrif14** [comment] 2019-07-09 06:38
i got the same issue this morning, yesterday my app just worked fine.

**Comment by adavid1** [comment] 2019-07-09 08:12
> i got the same issue this morning, yesterday my app just worked fine.

Same

**Comment by romidi** [comment] 2019-07-09 08:40
anybody know a workaround till it get fixed ?

**Comment by irmanfauzi** [comment] 2019-07-09 09:22
> anybody know a workaround till it get fixed ?

Look at previous thread. Something about changing "sts" to "args.cver".

https://github.com/Tyrrrz/YoutubeExplode/issues/266#issuecomment-509455528

**Comment by ConsultantsCombined** [comment] 2019-07-09 15:00
Go check out Allen Tomas fork for this he fixed it already. Just fork the project your self clone it make the change where Allen Tomas did and build it then import the new YouTube explode dll

**Comment by Tyrrrz** [comment] 2019-07-10 12:54
Closing as it's duplicate of #266

**Closed by Tyrrrz** 2019-07-10 12:54 UTC
Labels: duplicate
