### ISSUE TITLE
Getting error Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by Metinak47** [Tyrrrz/YoutubeExplode#815] opened 2024-09-23 19:12 UTC
### Version

v6.4.0

### Platform

.NET 7.0 / Windows 11

### Steps to reproduce

GetManifestAsync

### Details

Hi
When I want to call GetManifestAsync I have got error "Sign in to confirm you’re not a bot" after trace.
What I can to do?

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment] 2024-09-24 12:43
Duplicate of #794

**Closed by Tyrrrz** 2024-09-24 12:43 UTC
Labels: bug
