### ISSUE TITLE
Pushed a new version

### ISSUE THREAD

**Issue by ManamanaTheReal499** [Tyrrrz/YoutubeExplode#355] opened 2020-04-12 15:58 UTC
Still getting this error when attempting to download any of the media streams:

System.Net.Http.HttpRequestException: "Response status code does not indicate success: 403 (Forbidden)."

https://youtu.be/XqpNt2wiLEU

**Comment by Tyrrrz** [comment] 2020-04-12 15:59
Duplicate of #349

**Closed by Tyrrrz** 2020-04-12 15:59 UTC
Labels: duplicate
