### ISSUE TITLE
Download fail

### ISSUE THREAD

**Issue by booonzo** [Tyrrrz/YoutubeExplode#352] opened 2020-03-20 08:26 UTC
Hello guys!

Are you able to download this video: PMivT7MJ41M using 4.7.16 ?

**Comment by darianbenito** [comment] 2020-03-20 12:43
+1

**Comment by mirushas** [comment] 2020-03-20 16:28
+1 every download is failing.
31h ago everything worked fine.

**Comment by Tyrrrz** [comment] 2020-03-20 16:42
Hey guys. Try using the previous version.

**Comment by mirushas** [comment] 2020-03-20 17:13
Hey @Tyrrrz ,
I've already encounted this problem a few days ago, then I updated to the newest version this fixed the issue until 31h ago. Now it doesn't work with both versions.

**Comment by booonzo** [comment] 2020-03-20 18:24
Hey. I confirmed that version 4.7.15 seem to work fine.

**Comment by uponatime2019** [comment] 2020-03-21 05:20
I have to downgrade to 4.7.14

**Comment by Tyrrrz** [comment] 2020-03-21 14:12
There seem to be videos that work with 4.7.15, some that work with 4.7.16, and some that work with neither.

Closing as duplicate of #349 as it's really the same issue. Open for help because I can't dedicate time to it in the near future because I'm ill.

**Closed by Tyrrrz** 2020-03-21 14:12 UTC
Labels: duplicate
